version: '3'

networks:
  odoo-network:
    external: true
    name: odoo18-zerodowntime-network

services:
  odoo:
    image: odoo:18.0
    user: root
    container_name: odoo18-zerodowntime-blue
    networks:
      - odoo-network
    depends_on:
      - odoo-db-check
    ports:
      - "${ODOO_BLUE_HTTP_PORT}:8069"
      - "${ODOO_BLUE_LONGPOLLING_PORT}:8072"
    environment:
      HOST: db
      USER: '${POSTGRES_USER}'
      PASSWORD: '${POSTGRES_PASSWORD}'
      ODOO_SESSION_REDIS: '${ODOO_SESSION_REDIS}'
      ODOO_SESSION_REDIS_HOST: '${ODOO_SESSION_REDIS_HOST}'
      ODOO_SESSION_REDIS_PORT: '${ODOO_SESSION_REDIS_PORT}'
      ODOO_SESSION_REDIS_PASSWORD: '${ODOO_SESSION_REDIS_PASSWORD}'
      ODOO_SESSION_REDIS_SSL: '${ODOO_SESSION_REDIS_SSL}'
      ODOO_SESSION_REDIS_SSL_CERT_REQS: '${ODOO_SESSION_REDIS_SSL_CERT_REQS}'
      ODOO_SESSION_REDIS_CLUSTER: '${ODOO_SESSION_REDIS_CLUSTER}'
      ODOO_SESSION_REDIS_URL: '${ODOO_SESSION_REDIS_URL}'
      ODOO_SESSION_REDIS_PREFIX: '${ODOO_SESSION_REDIS_PREFIX}'
      ODOO_SESSION_REDIS_EXPIRATION: '${ODOO_SESSION_REDIS_EXPIRATION}'
      ODOO_SESSION_REDIS_EXPIRATION_ANONYMOUS: '${ODOO_SESSION_REDIS_EXPIRATION_ANONYMOUS}'
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf
      - ./odoo/logs:/etc/odoo/logs
      - ./etc/addons:/etc/odoo/addons
      - ./etc/filestore:/etc/odoo/filestore
      - ./etc/sessions:/etc/odoo/sessions
      - ./etc/requirements.txt:/etc/odoo/requirements.txt
      - ./odoo/custom-addons:/mnt/custom-addons
      - ./odoo/default-addons:/mnt/default-addons
    restart: always

  # dummy service to check if the database is ready before starting Odoo
  odoo-db-check:
    image: busybox
    container_name: odoo18-zerodowntime-blue-db-checker
    networks:
      - odoo-network
    command: sh -c "until nc -z db 5432; do echo waiting for db; sleep 2; done"
    restart: "no"
